# Generated by Django 6.0.6 on 2026-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la compétence (ex: Python, Arduino)')),
                ('categorie', models.CharField(choices=[('A', 'Électricité / Électronique'), ('B', 'Développement / Programmation'), ('C', 'Systèmes de Surveillance / Autre')], max_length=1, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_poste', models.CharField(max_length=150, verbose_name='Titre du poste')),
                ('entreprise', models.CharField(max_length=150, verbose_name='Entreprise / Organisation')),
                ('lieu', models.CharField(blank=True, max_length=100, verbose_name='Lieu (Ville, Pays)')),
                ('date_debut', models.CharField(max_length=50, verbose_name='Date de début (ex: Mai 2025)')),
                ('date_fin', models.CharField(blank=True, max_length=50, verbose_name='Date de fin (Laisser vide si actuel)')),
                ('description', models.TextField(verbose_name='Description des tâches / Réalisations')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage (Ex: 1 pour le plus récent)")),
            ],
            options={
                'verbose_name': 'Expérience Professionnelle',
                'verbose_name_plural': 'Expériences Professionnelles',
                'ordering': ['ordre', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=150, verbose_name='Diplôme ou Certification')),
                ('institution', models.CharField(max_length=150, verbose_name='Institution / École')),
                ('annee', models.CharField(max_length=50, verbose_name='Année ou Période (ex: 2025 - 2026)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['ordre', '-id'],
            },
        ),
    ]
