# Generated by Django 6.0.6 on 2026-06-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/icones/', verbose_name='Icône/Logo (Optionnel)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/', verbose_name='Image / Logo (Optionnel)'),
        ),
    ]
