# Generated by Django 6.0.6 on 2026-06-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_competence_icone_experience_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(default='Rovely Mayanda', max_length=100)),
                ('titre', models.CharField(default='Ingénieur en Électronique & Développeur', max_length=150)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='portfolio/profil/', verbose_name='Photo de profil')),
                ('a_propos', models.TextField(blank=True, verbose_name='À propos de moi / Introduction')),
                ('linkedin', models.URLField(blank=True, verbose_name='Lien LinkedIn (Optionnel)')),
                ('github', models.URLField(blank=True, verbose_name='Lien GitHub (Optionnel)')),
            ],
            options={
                'verbose_name': 'Mon Profil Général',
                'verbose_name_plural': 'Mon Profil Général',
            },
        ),
    ]
