# Generated by Django 6.0.6 on 2026-06-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la certification')),
                ('organisateur', models.CharField(max_length=150, verbose_name='Délivré par (ex: Coursera, Google)')),
                ('date', models.CharField(max_length=50, verbose_name="Date d'obtention")),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
            },
        ),
        migrations.RemoveField(
            model_name='competence',
            name='categorie',
        ),
        migrations.AddField(
            model_name='competence',
            name='description_details',
            field=models.TextField(blank=True, verbose_name='Détails/Sous-compétences (Optionnel)'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/icones/', verbose_name='Icône (Optionnel)'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la compétence'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_debut',
            field=models.CharField(max_length=50, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(verbose_name='Description des tâches'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='entreprise',
            field=models.CharField(max_length=150, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/', verbose_name='Logo/Image (Optionnel)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='lieu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='annee',
            field=models.CharField(max_length=50, verbose_name='Année / Période'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='diplome',
            field=models.CharField(max_length=150, verbose_name='Diplôme'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='institution',
            field=models.CharField(max_length=150, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nom_complet',
            field=models.CharField(default='Rovely Mayanda Manzanza', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='titre',
            field=models.CharField(default='Ingénieur Technicien Licencié en Électronique Industrielle', max_length=150),
        ),
    ]
