# Generated by Django 6.0.6 on 2026-06-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certification_remove_competence_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'expéditeur")),
                ('email', models.EmailField(max_length=254, verbose_name="Email de l'expéditeur")),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Corps du message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'abonnement")),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.CharField(default='14, Avenue Kimbuku, Q. Mateba, Ngaba, Kinshasa', max_length=255, verbose_name='Adresse / Quartier'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/cv/', verbose_name='Fichier CV PDF (Optionnel)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='rovelymayanda1@gmail.com', max_length=254, verbose_name='Adresse Email Professionnelle'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(default='+243 892 793 895', max_length=20, verbose_name='Numéro de Téléphone'),
        ),
    ]
