# Generated by Django 6.0.6 on 2026-06-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contactmessage_newslettersubscriber_profile_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Nom du projet')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('technologies', models.CharField(help_text='Ex: Python, Django, Arduino, GSM Module', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/projets/')),
                ('lien_github', models.URLField(blank=True, verbose_name='Lien vers le code (Optionnel)')),
                ('lien_demonstration', models.URLField(blank=True, verbose_name='Lien démo / Vidéo (Optionnel)')),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['ordre', '-id'],
            },
        ),
    ]
