# Generated by Django 6.0.6 on 2026-06-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='est_archive',
            field=models.BooleanField(default=False, verbose_name='Mettre dans les archives ?'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='organisateur',
            field=models.CharField(max_length=150, verbose_name='Délivré par'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='description_details',
            field=models.TextField(blank=True, verbose_name='Détails (Optionnel)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_fin',
            field=models.CharField(blank=True, max_length=50, verbose_name='Date de fin'),
        ),
    ]
