# Generated by Django 6.0.6 on 2026-06-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projet_est_archive_alter_certification_organisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('contenu', models.TextField()),
                ('image_couverture', models.ImageField(upload_to='blog/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
